steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/${PROJECT_ID}/weatherwise-ai:${COMMIT_SHA}', '.']

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/${PROJECT_ID}/weatherwise-ai:${COMMIT_SHA}']

  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'weatherwise-ai'
      - '--image'
      - 'gcr.io/${PROJECT_ID}/weatherwise-ai:${COMMIT_SHA}'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '8089'
      - '--set-env-vars'
      - 'NODE_ENV=production'
      # Replace "weather-gemini-service-url" with the name of your secret in Secret Manager.
      - '--set-secrets=CLOUD_RUN_URL=weather-gemini-service-url:latest'

images:
  - 'gcr.io/${PROJECT_ID}/weatherwise-ai:${COMMIT_SHA}'

options:
  logging: CLOUD_LOGGING_ONLY
